stages:
  - test
  - build
  # - deploy

code_quality:            
  image: node:16.16.0
  stage: test
  before_script:
    - npm ci -f
  script:
    - npm run eslint
    - npm run prettier
  only:                      
    - merge_requests

build:
  image: node:16.16.0
  stage: build
  before_script:
    - npm ci -f
  script:
    - npm run build
  artifacts:
    paths:
      - dist
  only:
    - merge_requests
    - main

# deploy:
#   image: alpine:latest                      
#   stage: deploy
#   before_script:
#     - apk update && apk add rsync openssh
#     - mkdir ~/.ssh                   
#     - chmod 600 ~/.ssh            
#     - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_rsa
#     - chmod 600 ~/.ssh/id_rsa
#     - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
#     - chmod 600 ~/.ssh/known_hosts
#   environment:
#     name: production
#   resource_group: production
#   script:
#     - rsync -a --delete dist/ sofya@95.216.189.150:/home/sofya/newsfeed
#   only:
#     - main